INSERT INTO country (country_name),
  VALUES
    ('Austria'),
    ('Belarus'),
    ('Belgium'),
    ('Bulgaria'),
    ('Czech Republic'),
    ('France'),
    ('Germany'),
    ('Hungary'),
    ('Italy'),
    ('Poland'),
    ('Romania'),
    ('Russia'),
    ('Serbia'),
    ('Spain'),
    ('Turkey'),
    ('Ukraine'),
    ('United Kingdom');